// examples/svelte/dynamic/src/RowVirtualizerDynamicWindow.svelte
<script lang="ts">
  import { faker } from '@faker-js/faker'
  import { createWindowVirtualizer } from '@tanstack/svelte-virtual'

  let virtualListEl = $state<HTMLDivElement | null>(null)
  let virtualItemEls = $state<HTMLDivElement[]>([])

  function randomNumber(min: number, max: number) {
    return faker.number.int({ min, max })
  }

  const sentences = new Array(10000)
    .fill(true)
    .map(() => faker.lorem.sentence(randomNumber(20, 70)))

  const count = sentences.length

  let virtualizer = $derived(
    createWindowVirtualizer<HTMLDivElement>({
      count,
      scrollMargin: virtualListEl?.offsetTop ?? 0,
      estimateSize: () => 45,
    }),
  )

  let items = $derived($virtualizer.getVirtualItems())

  $effect(() => {
    if (virtualItemEls.length)
      virtualItemEls.forEach((el) => $virtualizer.measureElement(el))
  })
</script>

<div>
  <div class="list scroll-container" bind:this={virtualListEl}>
    <div
      style="position: relative; height: {$virtualizer.getTotalSize()}px; width: 100%;"
    >
      <div
        style="position: absolute; top: 0; left: 0; width: 100%; transform: translateY({items[0]
          ? items[0].start - $virtualizer.options.scrollMargin
          : 0}px);"
      >
        {#each items as row, idx (row.index)}
          <div
            bind:this={virtualItemEls[idx]}
            data-index={row.index}
            class:list-item-even={row.index % 2 === 0}
            class:list-item-odd={row.index % 2 === 1}
          >
            <div style="padding: 10px 0;">
              <div>Row {row.index}</div>
              <div>{sentences[row.index]}</div>
            </div>
          </div>
        {/each}
      </div>
    </div>
  </div>
</div>

// examples/angular/dynamic/src/app/row-virtualizer-dynamic-window.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  afterNextRender,
  effect,
  signal,
  untracked,
  viewChild,
  viewChildren,
} from '@angular/core'
import { injectWindowVirtualizer } from '@tanstack/angular-virtual'
import { sentences } from './utils'

@Component({
  standalone: true,
  selector: 'row-virtualizer-dynamic',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div #scrollElement>
      <div
        style="position: relative; width: 100%;"
        [style.height.px]="virtualizer.getTotalSize()"
      >
        <div
          style="position: absolute; top: 0; left: 0; width: 100%;"
          [style.transform]="
            'translateY(' +
            (virtualizer.getVirtualItems()[0]
              ? virtualizer.getVirtualItems()[0].start - parentOffset()
              : 0) +
            'px)'
          "
        >
          @for (row of virtualizer.getVirtualItems(); track row.index) {
            <div
              #virtualItem
              [attr.data-index]="row.index"
              [class.list-item-even]="row.index % 2 === 0"
              [class.list-item-odd]="row.index % 2 !== 0"
            >
              <div style="padding: 10px 0">
                <div>Row {{ row.index }}</div>
                <div>{{ sentences[row.index] }}</div>
              </div>
            </div>
          }
        </div>
      </div>
    </div>
  `,
  styles: `
    .scroll-container {
      height: 400px;
      width: 400px;
      overflow-y: auto;
      contain: 'strict';
    }
  `,
})
export class RowVirtualizerDynamicWindow {
  scrollElement = viewChild<ElementRef<HTMLDivElement>>('scrollElement')

  parentOffset = signal(0)

  constructor() {
    afterNextRender(() =>
      this.parentOffset.set(this.scrollElement()!.nativeElement.offsetTop),
    )
  }

  virtualItems = viewChildren<ElementRef<HTMLDivElement>>('virtualItem')

  sentences = sentences

  count = this.sentences.length

  #measureItems = effect(() =>
    this.virtualItems().forEach((el) => {
      this.virtualizer.measureElement(el.nativeElement)
    }),
  )

  virtualizer = injectWindowVirtualizer(() => ({
    count: this.count,
    estimateSize: () => 150,
    scrollMargin: this.parentOffset(),
  }))
}
