// examples/vue/variable/src/components/GridVirtualizerVariable.vue
<template>
  <div
    ref="parentRef"
    class="List"
    style="height: 400px; width: 500px; overflow: auto"
  >
    <div
      :style="{
        height: `${totalSizeRows}px`,
        width: `${totalSizeColumns}px`,
        position: 'relative',
      }"
    >
      <template v-for="virtualRow in virtualRows" :key="virtualRow.index">
        <div
          v-for="virtualColumn in virtualColumns"
          :key="virtualColumn.index"
          :class="
            virtualColumn.index % 2
              ? virtualRow.index % 2 === 0
                ? 'ListItemOdd'
                : 'ListItemEven'
              : virtualRow.index % 2
              ? 'ListItemOdd'
              : 'ListItemEven'
          "
          :style="{
            position: 'absolute',
            top: 0,
            left: 0,
            width: `${columns[virtualColumn.index]}px`,
            height: `${rows[virtualRow.index]}px`,
            transform: `translateX(${virtualColumn.start}px) translateY(${virtualRow.start}px)`,
          }"
        >
          Cell {{ virtualRow.index }}, {{ virtualColumn.index }}
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, PropType } from 'vue'
import { useVirtualizer } from '@tanstack/vue-virtual'

const props = defineProps({
  rows: {
    type: Array as PropType<number[]>,
    default: () => [],
  },
  columns: {
    type: Array as PropType<number[]>,
    default: () => [],
  },
})

const parentRef = ref<HTMLElement | null>(null)

const rowVirtualizer = useVirtualizer({
  count: props.rows.length,
  getScrollElement: () => parentRef.value,
  estimateSize: (i) => props.rows[i],
  overscan: 5,
})

const columnVirtualizer = useVirtualizer({
  horizontal: true,
  count: props.columns.length,
  getScrollElement: () => parentRef.value,
  estimateSize: (i) => props.columns[i],
  overscan: 5,
})

const virtualRows = computed(() => rowVirtualizer.value.getVirtualItems())
const totalSizeRows = computed(() => rowVirtualizer.value.getTotalSize())

const virtualColumns = computed(() => columnVirtualizer.value.getVirtualItems())
const totalSizeColumns = computed(() => columnVirtualizer.value.getTotalSize())
</script>

// examples/angular/variable/src/app/grid-virtualizer-variable.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  input,
  viewChild,
} from '@angular/core'
import { injectVirtualizer } from '@tanstack/angular-virtual'

@Component({
  standalone: true,
  selector: 'grid-virtualizer-variable',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h3 style="margin-top: 2rem">Grid</h3>
    <div #scrollElement class="list scroll-container">
      <div
        style="position: relative; height: 100%;"
        [style.width.px]="columnVirtualizer.getTotalSize()"
        [style.height.px]="rowVirtualizer.getTotalSize()"
      >
        @for (
          row of rowVirtualizer.getVirtualItems();
          track row.index;
          let rowEven = $even
        ) {
          @for (
            col of columnVirtualizer.getVirtualItems();
            track col.index;
            let colEven = $even
          ) {
            <div
              [attr.data-index]="col.index"
              [class]="
                col.index % 2
                  ? row.index % 2 === 0
                    ? 'list-item-odd'
                    : 'list-item-even'
                  : row.index % 2
                    ? 'list-item-odd'
                    : 'list-item-even'
              "
              style="position: absolute; top: 0; left: 0;"
              [style.height.px]="row.size"
              [style.width.px]="col.size"
              [style.transform]="
                'translateX(' +
                col.start +
                'px)' +
                'translateY(' +
                row.start +
                'px)'
              "
            >
              Cell {{ row.index }}, {{ col.index }}
            </div>
          }
        }
      </div>
    </div>
  `,
  styles: `
    .scroll-container {
      height: 500px;
      width: 500px;
      overflow: auto;
    }
  `,
})
export class GridVirtualizerVariable {
  rows = input.required<number[]>()

  columns = input.required<number[]>()

  scrollElement = viewChild<ElementRef<HTMLDivElement>>('scrollElement')

  rowVirtualizer = injectVirtualizer(() => ({
    scrollElement: this.scrollElement(),
    count: 10000,
    estimateSize: (index) => this.rows()[index]!,
    overscan: 5,
  }))

  columnVirtualizer = injectVirtualizer(() => ({
    horizontal: true,
    scrollElement: this.scrollElement(),
    count: 10000,
    estimateSize: (index) => this.columns()[index]!,
    overscan: 5,
  }))
}
