// examples/angular/dynamic/src/app/grid-virtualizer-dynamic.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  afterNextRender,
  computed,
  effect,
  signal,
  viewChild,
  viewChildren,
} from '@angular/core'
import {
  injectVirtualizer,
  injectWindowVirtualizer,
} from '@tanstack/angular-virtual'
import { generateColumns, generateData } from './utils'

@Component({
  standalone: true,
  selector: 'grid-virtualizer-dynamic',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h3 style="margin-top: 2rem">Grid</h3>
    <div
      #scrollElement
      class="list scroll-container"
      style="border: 1px solid #c8c8c8"
    >
      <div
        style="position: relative;"
        [style.height.px]="rowVirtualizer.getTotalSize()"
      >
        @for (row of rowVirtualizer.getVirtualItems(); track row.key) {
          <div
            [attr.data-index]="row.index"
            #virtualRow
            style="position: absolute; top: 0; left: 0; display: flex;"
            [style.transform]="
              'translateY(' +
              (row.start - rowVirtualizer.options().scrollMargin) +
              'px)'
            "
          >
            <div [style.width.px]="width()[0]"></div>
            @for (col of columnVirtualizer.getVirtualItems(); track col.key) {
              <div
                style="border-bottom: 1px solid #c8c8c8; border-right: 1px solid #c8c8c8; padding: 7px 12px"
                [style.minHeight.px]="row.index === 0 ? 50 : row.size"
                [style.width.px]="getColumnWidth(col.index)"
              >
                <div>
                  {{
                    row.index === 0
                      ? columns[col.index].name
                      : data[row.index][col.index]
                  }}
                </div>
              </div>
            }
            <div [style.width.px]="width()[1]"></div>
          </div>
        }
      </div>
    </div>
  `,
  styles: `
    .scroll-container {
      overflow: auto;
    }
  `,
})
export class GridVirtualizerDynamic {
  scrollElement = viewChild<ElementRef<HTMLDivElement>>('scrollElement')
  columns = generateColumns(30)
  data = generateData(this.columns)

  parentOffset = signal(0)

  constructor() {
    afterNextRender(() =>
      this.parentOffset.set(this.scrollElement()!.nativeElement.offsetTop),
    )
  }

  getColumnWidth = (index: number) => this.columns[index].width

  rowVirtualizer = injectWindowVirtualizer(() => ({
    count: this.data.length,
    estimateSize: () => 350,
    overscan: 5,
    scrollMargin: this.parentOffset(),
  }))

  columnVirtualizer = injectVirtualizer(() => ({
    horizontal: true,
    scrollElement: this.scrollElement(),
    count: this.columns.length,
    estimateSize: this.getColumnWidth,
    overscan: 5,
  }))

  width = computed(
    () => {
      const virtualColumns = this.columnVirtualizer.getVirtualItems()
      return virtualColumns.length > 0
        ? [
            virtualColumns[0].start,
            this.columnVirtualizer.getTotalSize() -
              virtualColumns[virtualColumns.length - 1].end,
          ]
        : [0, 0]
    },
    { equal: (a, b) => a[0] === b[0] && a[1] === b[1] },
  )

  virtualRows = viewChildren<ElementRef<HTMLDivElement>>('virtualRow')

  #measureItems = effect(() =>
    this.virtualRows().forEach((el) => {
      this.rowVirtualizer.measureElement(el.nativeElement)
    }),
  )
}

// examples/vue/dynamic/src/components/GridVirtualizerDynamic.vue
<template>
  <div ref="parentRef" style="overflow-y: auto; border: 1px solid #c8c8c8">
    <div
      :style="{
        height: `${totalSize}px`,
        position: 'relative',
      }"
    >
      <template v-for="virtualRow in virtualRows" :key="virtualRow.key">
        <div
          :data-index="virtualRow.index"
          :ref="measureElement"
          :style="{
            position: 'absolute',
            top: 0,
            left: 0,
            transform: `translateY(${
              virtualRow.start - rowVirtualizer.options.scrollMargin
            }px)`,
            display: 'flex',
          }"
        >
          <div :style="{ width: `${width[0]}px` }" />
          <template
            v-for="virtualColumn in virtualColumns"
            :key="virtualColumn.key"
          >
            <div
              :style="{
                minHeight: virtualRow.index === 0 ? 50 : virtualRow.size,
                width: `${getColumnWidth(virtualColumn.index)}px`,
                borderBottom: '1px solid #c8c8c8',
                borderRight: '1px solid #c8c8c8',
                padding: '7px 12px',
              }"
            >
              <div v-if="virtualRow.index === 0">
                {{ columns[virtualColumn.index].name }}
              </div>
              <div v-else>
                {{ data[virtualRow.index][virtualColumn.index] }}
              </div>
            </div>
          </template>
          <div :style="{ width: `${width[1]}px` }" />
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, type VNodeRef } from 'vue'
import { useWindowVirtualizer, useVirtualizer } from '@tanstack/vue-virtual'
import { generateData, generateColumns } from './utils'

const columns = generateColumns(30)
const data = generateData(columns)

const parentRef = ref<HTMLElement | null>(null)

const parentOffsetRef = ref(0)

onMounted(() => {
  parentOffsetRef.value = parentRef.value?.offsetTop ?? 0
})

const rowVirtualizerOptions = computed(() => {
  return {
    count: data.length,
    estimateSize: () => 350,
    overscan: 5,
    scrollMargin: parentOffsetRef.value,
  }
})

const rowVirtualizer = useWindowVirtualizer(rowVirtualizerOptions)

const virtualRows = computed(() => rowVirtualizer.value.getVirtualItems())

const totalSize = computed(() => rowVirtualizer.value.getTotalSize())

const getColumnWidth = (index: number) => columns[index].width

const columnVirtualizerOptions = computed(() => {
  return {
    horizontal: true,
    count: columns.length,
    getScrollElement: () => parentRef.value,
    estimateSize: getColumnWidth,
    overscan: 5,
  }
})

const columnVirtualizer = useVirtualizer(columnVirtualizerOptions)

const virtualColumns = computed(() => columnVirtualizer.value.getVirtualItems())

const width = computed(() => {
  return virtualColumns.value.length > 0
    ? [
        virtualColumns.value[0].start,
        columnVirtualizer.value.getTotalSize() -
          virtualColumns.value[virtualColumns.value.length - 1].end,
      ]
    : [0, 0]
})

const measureElement = (el: VNodeRef & HTMLElement) => {
  if (!el) {
    return
  }

  rowVirtualizer.value.measureElement(el)

  return el
}
</script>
