// examples/svelte/fixed/src/GridVirtualizerFixed.svelte
<script lang="ts">
  import { createVirtualizer } from '@tanstack/svelte-virtual'

  let virtualListEl: HTMLDivElement

  $: rowVirtualizer = createVirtualizer<HTMLDivElement, HTMLDivElement>({
    count: 10000,
    getScrollElement: () => virtualListEl,
    estimateSize: () => 35,
    overscan: 5,
  })

  $: columnVirtualizer = createVirtualizer<HTMLDivElement, HTMLDivElement>({
    horizontal: true,
    count: 10000,
    getScrollElement: () => virtualListEl,
    estimateSize: () => 100,
    overscan: 5,
  })
</script>

<div class="list scroll-container" bind:this={virtualListEl}>
  <div
    style="position: relative; height: {$rowVirtualizer.getTotalSize()}px; width: {$columnVirtualizer.getTotalSize()}px;"
  >
    {#each $rowVirtualizer.getVirtualItems() as row (row.index)}
      {#each $columnVirtualizer.getVirtualItems() as col (col.index)}
        <div
          class={col.index % 2
            ? row.index % 2 === 0
              ? 'list-item-odd'
              : 'list-item-even'
            : row.index % 2
              ? 'list-item-odd'
              : 'list-item-even'}
          style="position: absolute; top: 0; left: 0; width: {col.size}px; height: {row.size}px; transform: translateX({col.start}px) translateY({row.start}px);"
        >
          Cell {row.index}, {col.index}
        </div>
      {/each}
    {/each}
  </div>
</div>

<style>
  .scroll-container {
    height: 500px;
    width: 500px;
    overflow: auto;
  }
</style>

// examples/angular/fixed/src/app/grid-virtualizer-fixed.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  viewChild,
} from '@angular/core'
import { injectVirtualizer } from '@tanstack/angular-virtual'

@Component({
  standalone: true,
  selector: 'grid-virtualizer-fixed',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h3 style="margin-top: 2rem">Grid</h3>
    <div #scrollElement class="list scroll-container">
      <div
        style="position: relative; height: 100%;"
        [style.width.px]="columnVirtualizer.getTotalSize()"
        [style.height.px]="rowVirtualizer.getTotalSize()"
      >
        @for (
          row of rowVirtualizer.getVirtualItems();
          track row.index;
          let rowEven = $even
        ) {
          @for (
            col of columnVirtualizer.getVirtualItems();
            track col.index;
            let colEven = $even
          ) {
            <div
              [attr.data-index]="col.index"
              [class]="
                col.index % 2
                  ? row.index % 2 === 0
                    ? 'list-item-odd'
                    : 'list-item-even'
                  : row.index % 2
                    ? 'list-item-odd'
                    : 'list-item-even'
              "
              style="position: absolute; top: 0; left: 0;"
              [style.height.px]="row.size"
              [style.width.px]="col.size"
              [style.transform]="
                'translateX(' +
                col.start +
                'px)' +
                'translateY(' +
                row.start +
                'px)'
              "
            >
              Cell {{ row.index }}, {{ col.index }}
            </div>
          }
        }
      </div>
    </div>
  `,
  styles: `
    .scroll-container {
      height: 500px;
      width: 500px;
      overflow: auto;
    }
  `,
})
export class GridVirtualizerFixed {
  scrollElement = viewChild<ElementRef<HTMLDivElement>>('scrollElement')

  rowVirtualizer = injectVirtualizer(() => ({
    scrollElement: this.scrollElement(),
    count: 10000,
    estimateSize: () => 35,
    overscan: 5,
  }))

  columnVirtualizer = injectVirtualizer(() => ({
    horizontal: true,
    scrollElement: this.scrollElement(),
    count: 10000,
    estimateSize: () => 100,
    overscan: 5,
  }))
}
