// examples/vue/dynamic/src/components/GridVirtualizerDynamic.vue
<template>
  <div ref="parentRef" style="overflow-y: auto; border: 1px solid #c8c8c8">
    <div
      :style="{
        height: `${totalSize}px`,
        position: 'relative',
      }"
    >
      <template v-for="virtualRow in virtualRows" :key="virtualRow.key">
        <div
          :data-index="virtualRow.index"
          :ref="measureElement"
          :style="{
            position: 'absolute',
            top: 0,
            left: 0,
            transform: `translateY(${
              virtualRow.start - rowVirtualizer.options.scrollMargin
            }px)`,
            display: 'flex',
          }"
        >
          <div :style="{ width: `${width[0]}px` }" />
          <template
            v-for="virtualColumn in virtualColumns"
            :key="virtualColumn.key"
          >
            <div
              :style="{
                minHeight: virtualRow.index === 0 ? 50 : virtualRow.size,
                width: `${getColumnWidth(virtualColumn.index)}px`,
                borderBottom: '1px solid #c8c8c8',
                borderRight: '1px solid #c8c8c8',
                padding: '7px 12px',
              }"
            >
              <div v-if="virtualRow.index === 0">
                {{ columns[virtualColumn.index].name }}
              </div>
              <div v-else>
                {{ data[virtualRow.index][virtualColumn.index] }}
              </div>
            </div>
          </template>
          <div :style="{ width: `${width[1]}px` }" />
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, type VNodeRef } from 'vue'
import { useWindowVirtualizer, useVirtualizer } from '@tanstack/vue-virtual'
import { generateData, generateColumns } from './utils'

const columns = generateColumns(30)
const data = generateData(columns)

const parentRef = ref<HTMLElement | null>(null)

const parentOffsetRef = ref(0)

onMounted(() => {
  parentOffsetRef.value = parentRef.value?.offsetTop ?? 0
})

const rowVirtualizerOptions = computed(() => {
  return {
    count: data.length,
    estimateSize: () => 350,
    overscan: 5,
    scrollMargin: parentOffsetRef.value,
  }
})

const rowVirtualizer = useWindowVirtualizer(rowVirtualizerOptions)

const virtualRows = computed(() => rowVirtualizer.value.getVirtualItems())

const totalSize = computed(() => rowVirtualizer.value.getTotalSize())

const getColumnWidth = (index: number) => columns[index].width

const columnVirtualizerOptions = computed(() => {
  return {
    horizontal: true,
    count: columns.length,
    getScrollElement: () => parentRef.value,
    estimateSize: getColumnWidth,
    overscan: 5,
  }
})

const columnVirtualizer = useVirtualizer(columnVirtualizerOptions)

const virtualColumns = computed(() => columnVirtualizer.value.getVirtualItems())

const width = computed(() => {
  return virtualColumns.value.length > 0
    ? [
        virtualColumns.value[0].start,
        columnVirtualizer.value.getTotalSize() -
          virtualColumns.value[virtualColumns.value.length - 1].end,
      ]
    : [0, 0]
})

const measureElement = (el: VNodeRef & HTMLElement) => {
  if (!el) {
    return
  }

  rowVirtualizer.value.measureElement(el)

  return el
}
</script>

// examples/svelte/dynamic/src/GridVirtualizerDynamic.svelte
<script lang="ts">
  import { createVirtualizer } from '@tanstack/svelte-virtual'

  let virtualListEl: HTMLDivElement

  $: rowVirtualizer = createVirtualizer<HTMLDivElement, HTMLDivElement>({
    count: 10000,
    getScrollElement: () => virtualListEl,
    estimateSize: () => 35,
    overscan: 5,
  })

  $: columnVirtualizer = createVirtualizer<HTMLDivElement, HTMLDivElement>({
    horizontal: true,
    count: 10000,
    getScrollElement: () => virtualListEl,
    estimateSize: () => 100,
    overscan: 5,
  })
</script>

<div class="list scroll-container" bind:this={virtualListEl}>
  <div
    style="position: relative; height: {$rowVirtualizer.getTotalSize()}px; width: {$columnVirtualizer.getTotalSize()}px;"
  >
    {#each $rowVirtualizer.getVirtualItems() as row (row.index)}
      {#each $columnVirtualizer.getVirtualItems() as col (col.index)}
        <div
          class={col.index % 2
            ? row.index % 2 === 0
              ? 'list-item-odd'
              : 'list-item-even'
            : row.index % 2
            ? 'list-item-odd'
            : 'list-item-even'}
          style="position: absolute; top: 0; left: 0; width: {col.size}px; height: {row.size}px; transform: translateX({col.start}px) translateY({row.start}px)"
        >
          Cell {row.index}, {col.index}
        </div>
      {/each}
    {/each}
  </div>
</div>

<style>
  .scroll-container {
    height: 500px;
    width: 500px;
    overflow: auto;
  }
</style>
