// packages/lit-virtual/src/index.ts
import { ReactiveController, ReactiveControllerHost } from 'lit'
import {
  PartialKeys,
  Virtualizer,
  VirtualizerOptions,
  observeWindowOffset,
  observeWindowRect,
} from '@tanstack/virtual-core'
import {
  observeElementOffset,
  observeElementRect,
  windowScroll,
  elementScroll,
} from '@tanstack/virtual-core'

class VirtualizerControllerBase<
  TScrollElement extends Element | Window,
  TItemElement extends Element,
> implements ReactiveController
{
  host: ReactiveControllerHost

  private readonly virtualizer: Virtualizer<TScrollElement, TItemElement>

  private cleanup: () => void = () => {}

  constructor(
    host: ReactiveControllerHost,
    options: VirtualizerOptions<TScrollElement, TItemElement>,
  ) {
    ;(this.host = host).addController(this)

    const resolvedOptions: VirtualizerOptions<TScrollElement, TItemElement> = {
      ...options,
      onChange: (instance, sync) => {
        this.host.updateComplete.then(() => this.host.requestUpdate())
        options.onChange?.(instance, sync)
      },
    }
    this.virtualizer = new Virtualizer(resolvedOptions)
  }

  public getVirtualizer() {
    return this.virtualizer
  }

  async hostConnected() {
    this.cleanup = this.virtualizer._didMount()
    this.virtualizer._willUpdate()
    await this.host.updateComplete
    this.host.requestUpdate()
    this.virtualizer.measure()
  }

  hostUpdated() {
    this.virtualizer._willUpdate()
  }

  hostDisconnected() {
    this.cleanup()
  }
}

export class VirtualizerController<
  TScrollElement extends Element,
  TItemElement extends Element,
> extends VirtualizerControllerBase<TScrollElement, TItemElement> {
  constructor(
    host: ReactiveControllerHost,
    options: PartialKeys<
      VirtualizerOptions<TScrollElement, TItemElement>,
      'observeElementRect' | 'observeElementOffset' | 'scrollToFn'
    >,
  ) {
    super(host, {
      observeElementRect: observeElementRect,
      observeElementOffset: observeElementOffset,
      scrollToFn: elementScroll,
      ...options,
    })
  }
}

export class WindowVirtualizerController<
  TItemElement extends Element,
> extends VirtualizerControllerBase<Window, TItemElement> {
  constructor(
    host: ReactiveControllerHost,
    options: PartialKeys<
      VirtualizerOptions<Window, TItemElement>,
      | 'getScrollElement'
      | 'observeElementRect'
      | 'observeElementOffset'
      | 'scrollToFn'
    >,
  ) {
    super(host, {
      getScrollElement: () => (typeof document !== 'undefined' ? window : null),
      observeElementRect: observeWindowRect,
      observeElementOffset: observeWindowOffset,
      scrollToFn: windowScroll,
      initialOffset: () =>
        typeof document !== 'undefined' ? window.scrollY : 0,
      ...options,
    })
  }
}

// packages/solid-virtual/src/index.tsx
import {
  Virtualizer,
  elementScroll,
  observeElementOffset,
  observeElementRect,
  observeWindowOffset,
  observeWindowRect,
  windowScroll,
} from '@tanstack/virtual-core'

import {
  createComputed,
  createSignal,
  mergeProps,
  onCleanup,
  onMount,
} from 'solid-js'
import { createStore, reconcile } from 'solid-js/store'
import type { PartialKeys, VirtualizerOptions } from '@tanstack/virtual-core'

export * from '@tanstack/virtual-core'

function createVirtualizerBase<
  TScrollElement extends Element | Window,
  TItemElement extends Element,
>(
  options: VirtualizerOptions<TScrollElement, TItemElement>,
): Virtualizer<TScrollElement, TItemElement> {
  const resolvedOptions: VirtualizerOptions<TScrollElement, TItemElement> =
    mergeProps(options)

  const instance = new Virtualizer<TScrollElement, TItemElement>(
    resolvedOptions,
  )

  const [virtualItems, setVirtualItems] = createStore(
    instance.getVirtualItems(),
  )
  const [totalSize, setTotalSize] = createSignal(instance.getTotalSize())

  const handler = {
    get(
      target: Virtualizer<TScrollElement, TItemElement>,
      prop: keyof Virtualizer<TScrollElement, TItemElement>,
    ) {
      switch (prop) {
        case 'getVirtualItems':
          return () => virtualItems
        case 'getTotalSize':
          return () => totalSize()
        default:
          return Reflect.get(target, prop)
      }
    },
  }

  const virtualizer = new Proxy(instance, handler)
  virtualizer.setOptions(resolvedOptions)

  onMount(() => {
    const cleanup = virtualizer._didMount()
    virtualizer._willUpdate()
    onCleanup(cleanup)
  })

  createComputed(() => {
    virtualizer.setOptions(
      mergeProps(resolvedOptions, options, {
        onChange: (
          instance: Virtualizer<TScrollElement, TItemElement>,
          sync: boolean,
        ) => {
          instance._willUpdate()
          setVirtualItems(
            reconcile(instance.getVirtualItems(), {
              key: 'index',
            }),
          )
          setTotalSize(instance.getTotalSize())
          options.onChange?.(instance, sync)
        },
      }),
    )
    virtualizer.measure()
  })

  return virtualizer
}

export function createVirtualizer<
  TScrollElement extends Element,
  TItemElement extends Element,
>(
  options: PartialKeys<
    VirtualizerOptions<TScrollElement, TItemElement>,
    'observeElementRect' | 'observeElementOffset' | 'scrollToFn'
  >,
): Virtualizer<TScrollElement, TItemElement> {
  return createVirtualizerBase<TScrollElement, TItemElement>(
    mergeProps(
      {
        observeElementRect: observeElementRect,
        observeElementOffset: observeElementOffset,
        scrollToFn: elementScroll,
      },
      options,
    ),
  )
}

export function createWindowVirtualizer<TItemElement extends Element>(
  options: PartialKeys<
    VirtualizerOptions<Window, TItemElement>,
    | 'getScrollElement'
    | 'observeElementRect'
    | 'observeElementOffset'
    | 'scrollToFn'
  >,
): Virtualizer<Window, TItemElement> {
  return createVirtualizerBase<Window, TItemElement>(
    mergeProps(
      {
        getScrollElement: () =>
          typeof document !== 'undefined' ? window : null,
        observeElementRect: observeWindowRect,
        observeElementOffset: observeWindowOffset,
        scrollToFn: windowScroll,
        initialOffset: () =>
          typeof document !== 'undefined' ? window.scrollY : 0,
      },
      options,
    ),
  )
}
