// examples/angular/fixed/src/app/column-virtualizer-fixed.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  viewChild,
} from '@angular/core'
import { injectVirtualizer } from '@tanstack/angular-virtual'

@Component({
  standalone: true,
  selector: 'column-virtualizer-fixed',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h3 style="margin-top: 2rem">Columns</h3>
    <div #scrollElement class="list scroll-container">
      <div
        style="position: relative; height: 100%;"
        [style.width.px]="virtualizer.getTotalSize()"
      >
        @for (col of virtualizer.getVirtualItems(); track col.index) {
          <div
            [attr.data-index]="col.index"
            [class.list-item-even]="col.index % 2 === 0"
            [class.list-item-odd]="col.index % 2 !== 0"
            style="position: absolute; top: 0; left: 0; height: 100%;"
            [style.width.px]="col.size"
            [style.transform]="'translateX(' + col.start + 'px)'"
          >
            Col {{ col.index }}
          </div>
        }
      </div>
    </div>
  `,
  styles: `
    .scroll-container {
      height: 100px;
      width: 400px;
      overflow: auto;
    }
  `,
})
export class ColumnVirtualizerFixed {
  scrollElement = viewChild<ElementRef<HTMLDivElement>>('scrollElement')

  virtualizer = injectVirtualizer(() => ({
    horizontal: true,
    scrollElement: this.scrollElement(),
    count: 10000,
    estimateSize: () => 100,
    overscan: 5,
  }))
}

// examples/svelte/fixed/src/ColumnVirtualizerFixed.svelte
<script lang="ts">
  import { createVirtualizer } from '@tanstack/svelte-virtual'

  let virtualListEl: HTMLDivElement

  $: virtualizer = createVirtualizer<HTMLDivElement, HTMLDivElement>({
    horizontal: true,
    count: 10000,
    getScrollElement: () => virtualListEl,
    estimateSize: () => 100,
    overscan: 5,
  })
</script>

<div class="list scroll-container" bind:this={virtualListEl}>
  <div
    style="position: relative; height: 100%; width: {$virtualizer.getTotalSize()}px;"
  >
    {#each $virtualizer.getVirtualItems() as col (col.index)}
      <div
        class:list-item-even={col.index % 2 === 0}
        class:list-item-odd={col.index % 2 === 1}
        style="position: absolute; top: 0; left: 0; width: {col.size}px; height: 100%; transform: translateX({col.start}px)"
      >
        Column {col.index}
      </div>
    {/each}
  </div>
</div>

<style>
  .scroll-container {
    height: 100px;
    width: 400px;
    overflow: auto;
  }
</style>
