// examples/vue/fixed/src/components/GridVirtualizerFixed.vue
<template>
  <div
    ref="parentRef"
    class="List"
    style="height: 500px; width: 500px; overflow: auto"
  >
    <div
      :style="{
        height: `${totalSizeRows}px`,
        width: `${totalSizeColumns}px`,
        position: 'relative',
      }"
    >
      <template v-for="virtualRow in virtualRows" :key="virtualRow.index">
        <template
          v-for="virtualColumn in columnVirtualizer.getVirtualItems()"
          :key="virtualColumn.index"
        >
          <div
            :class="
              virtualColumn.index % 2
                ? virtualRow.index % 2 === 0
                  ? 'ListItemOdd'
                  : 'ListItemEven'
                : virtualRow.index % 2
                ? 'ListItemOdd'
                : 'ListItemEven'
            "
            :style="{
              position: 'absolute',
              top: 0,
              left: 0,
              width: `${virtualColumn.size}px`,
              height: `${virtualRow.size}px`,
              transform: `translateX(${virtualColumn.start}px) translateY(${virtualRow.start}px)`,
            }"
          >
            Cell {{ virtualRow.index }}, {{ virtualColumn.index }}
          </div>
        </template>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useVirtualizer } from '@tanstack/vue-virtual'

const parentRef = ref<HTMLElement | null>(null)

const rowVirtualizer = useVirtualizer({
  count: 10000,
  getScrollElement: () => parentRef.value,
  estimateSize: () => 35,
  overscan: 5,
})

const columnVirtualizer = useVirtualizer({
  horizontal: true,
  count: 10000,
  getScrollElement: () => parentRef.value,
  estimateSize: () => 100,
  overscan: 5,
})

const virtualRows = computed(() => rowVirtualizer.value.getVirtualItems())
const totalSizeRows = computed(() => rowVirtualizer.value.getTotalSize())

const totalSizeColumns = computed(() => columnVirtualizer.value.getTotalSize())
</script>

// examples/svelte/fixed/src/GridVirtualizerFixed.svelte
<script lang="ts">
  import { createVirtualizer } from '@tanstack/svelte-virtual'

  let virtualListEl: HTMLDivElement

  $: rowVirtualizer = createVirtualizer<HTMLDivElement, HTMLDivElement>({
    count: 10000,
    getScrollElement: () => virtualListEl,
    estimateSize: () => 35,
    overscan: 5,
  })

  $: columnVirtualizer = createVirtualizer<HTMLDivElement, HTMLDivElement>({
    horizontal: true,
    count: 10000,
    getScrollElement: () => virtualListEl,
    estimateSize: () => 100,
    overscan: 5,
  })
</script>

<div class="list scroll-container" bind:this={virtualListEl}>
  <div
    style="position: relative; height: {$rowVirtualizer.getTotalSize()}px; width: {$columnVirtualizer.getTotalSize()}px;"
  >
    {#each $rowVirtualizer.getVirtualItems() as row (row.index)}
      {#each $columnVirtualizer.getVirtualItems() as col (col.index)}
        <div
          class={col.index % 2
            ? row.index % 2 === 0
              ? 'list-item-odd'
              : 'list-item-even'
            : row.index % 2
              ? 'list-item-odd'
              : 'list-item-even'}
          style="position: absolute; top: 0; left: 0; width: {col.size}px; height: {row.size}px; transform: translateX({col.start}px) translateY({row.start}px);"
        >
          Cell {row.index}, {col.index}
        </div>
      {/each}
    {/each}
  </div>
</div>

<style>
  .scroll-container {
    height: 500px;
    width: 500px;
    overflow: auto;
  }
</style>
